import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from '../dist/server/index.js';
import {freshState} from '../worker/domain.mjs';
const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_tense_human_fly.sql',import.meta.url),'utf8'));
function prepared(query,args=[]){return {bind(...values){return prepared(query,values);},async first(){return sql.prepare(query).get(...args)||null;},async all(){return {results:sql.prepare(query).all(...args)};},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}};}};}
const DB={prepare:query=>prepared(query),async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}};
const blobs=new Map(),BUCKET={async put(k,v){blobs.set(k,v);}};
const s=freshState();s.settings.last_price_success=new Date().toISOString();s.holdings=[{id:1,source_row:2,name:'Lightning Bolt',set_code:'m11',collector_number:'146',printing_key:'m11:146',quantity:2,finish:'nonfoil',card_type:'Instant',color:'Red',rarity:'common',deck_label:'',notes:''},{id:2,source_row:2,name:'Lightning Bolt',set_code:'m11',collector_number:'146',printing_key:'m11:146',quantity:1,finish:'foil',card_type:'Instant',color:'Red',rarity:'common',deck_label:'',notes:''}];s.matches['m11:146']={status:'unresolved'};sql.prepare('INSERT INTO vault (id,revision,payload) VALUES(1,0,?)').run(JSON.stringify(s));
const env={DB,BUCKET};const tasks=[];const ctx={waitUntil:p=>tasks.push(p)};
const request=(path,method='GET',data)=>worker.fetch(new Request('https://vault.example/api'+path,{method,body:data===undefined?undefined:JSON.stringify(data),headers:data===undefined?{}:{'Content-Type':'application/json'}}),env,ctx);
const flush=async()=>{await Promise.all(tasks.splice(0));};
const originalFetch=globalThis.fetch;
test('Hosted refresh matches printing/finish; offline failures preserve cached prices',async()=>{const card={id:'00000000-0000-0000-0000-000000000001',oracle_id:'bolt',name:'Lightning Bolt',set:'m11',collector_number:'146',prices:{eur:'2.50',eur_foil:'7.00'},legalities:{modern:'legal'}};globalThis.fetch=async()=>new Response(JSON.stringify({data:[card],not_found:[]}),{headers:{'Content-Type':'application/json'}});try{assert.equal((await request('/prices/refresh?force=true','POST',{})).status,200);await flush();let collection=await (await request('/collection')).json();assert.equal(collection[0].value,12);assert.equal(collection[0].priced_copies,3);globalThis.fetch=async()=>{throw Error('network unavailable');};await request('/prices/refresh?force=true','POST',{});await flush();collection=await (await request('/collection')).json();assert.equal(collection[0].value,12);assert.equal(collection[0].match_status,'matched');const state=await (await request('/state')).json();assert.match(state.price_job.error,/unavailable/);assert.equal(state.price_job.running,false);}finally{globalThis.fetch=originalFetch;}});
test('Export filtering and JSON backups use saved state',async()=>{const result=await request('/export?kind=collection&q=missing');assert.equal(await result.text(),'');const backup=await (await request('/backup')).json();assert.equal(backup.state.holdings.length,2);assert.equal(backup.cards.length,1);assert.equal(blobs.size,1);});
test('Printing name mismatches are quarantined before valuation',async()=>{const row=sql.prepare('SELECT payload FROM vault WHERE id=1').get();const state=JSON.parse(row.payload);state.matches['m11:146']={status:'unresolved'};sql.prepare('UPDATE vault SET payload=? WHERE id=1').run(JSON.stringify(state));globalThis.fetch=async()=>new Response(JSON.stringify({data:[{id:'wrong',oracle_id:'wrong',name:'Not Lightning Bolt',set:'m11',collector_number:'146',prices:{eur:'99',eur_foil:'99'}}]}));try{await request('/prices/refresh?force=true','POST',{});await flush();const rows=await (await request('/collection')).json();assert.equal(rows[0].match_status,'name_mismatch');assert.equal(rows[0].value,null);}finally{globalThis.fetch=originalFetch;}});
