import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {Inventory,freshState,applySnapshot,parseDecklist,reductions,textExport} from '../worker/domain.mjs';
import {parseWorkbook} from '../worker/importer.mjs';
const originalPath=new URL('../MagicTheGatheringInventory.xlsx',import.meta.url);
const hasOriginal=existsSync(originalPath);
const seed=await parseWorkbook(readFileSync(hasOriginal?originalPath:new URL('../sample-inventory.xlsx',import.meta.url)));
if(!seed.holdings.some(h=>h.deck_label))seed.holdings[0].deck_label='Fixture deck';
const initial=()=>{const s=freshState();applySnapshot(s,seed,'initial');return s;};
test('Original workbook totals, duplicate preservation, invalid row, and foil splitting',{skip:!hasOriginal},async()=>{const p=await parseWorkbook(readFileSync(new URL('../MagicTheGatheringInventory.xlsx',import.meta.url)));assert.equal(p.rows,679);assert.equal(p.copies,892);assert.equal(p.fingerprint,seed.fingerprint);assert.equal(p.holdings.filter(h=>h.finish==='foil').reduce((a,h)=>a+h.quantity,0),48);assert.equal(p.issues.length,1);assert.equal(p.issues[0].source_row,253);assert.equal(new Inventory(initial()).collection().length,655);assert.equal(new Set(p.holdings.map(h=>h.name)).size,607);assert.deepEqual(p.holdings,seed.holdings);});
test('Repeat snapshots preserve quantities and target edits',()=>{const s=initial();s.decks[0].name='Edited deck';s.entries.push({id:9000,deck_id:s.decks[0].id,name:'Unowned card',quantity:1,zone:'sideboard',printing_key:null});applySnapshot(s,seed,'again');assert.equal(s.holdings.reduce((a,h)=>a+h.quantity,0),seed.copies);assert.equal(s.decks.length,new Set(seed.holdings.map(h=>h.deck_label).filter(Boolean)).size);assert.equal(s.decks[0].name,'Edited deck');assert(s.entries.some(e=>e.name==='Unowned card'));});
test('Reduced counts are surfaced and unknown prices stay unknown',()=>{const s=initial();const next=structuredClone(seed.holdings);next[0].quantity--;assert.equal(reductions(s.holdings,next).length,1);const rows=new Inventory(s).collection();assert(rows.every(c=>c.value===null));assert.equal(rows.reduce((a,c)=>a+c.priced_copies,0),0);});
function sharedState(){const s=freshState();s.holdings=[{id:1,source_row:2,name:'Sol Ring',printing_key:'cmm:1',set_code:'cmm',collector_number:'1',quantity:1,finish:'nonfoil',deck_label:'',notes:''}];s.decks=[{id:1,name:'A',active:1,format:'commander',priority:0},{id:2,name:'B',active:1,format:'commander',priority:0}];s.entries=[{id:1,deck_id:1,name:'Sol Ring',quantity:1,zone:'main',printing_key:null},{id:2,deck_id:2,name:'Sol Ring',quantity:1,zone:'main',printing_key:null}];return s;}
test('Simultaneous decks allocate each physical copy once; shared decks reuse it',()=>{const inv=new Inventory(sharedState());assert.equal(inv.wishlist(new Set([1,2]),'assembled').copies,1);assert.equal(inv.wishlist(new Set([1,2]),'shared').copies,0);assert.equal(inv.deck(1).missing+inv.deck(2).missing,0);assert.equal(inv.deck(1).missing_now+inv.deck(2).missing_now,1);});
test('Exact printing is reserved before flexible target',()=>{const s=sharedState();s.entries[1].printing_key='cmm:1';const inv=new Inventory(s);assert.equal(inv.deck(2).missing_now,0);assert.equal(inv.deck(1).missing_now,1);});
test('Canonical double-faced names and finish-specific currency prices',()=>{const s=sharedState();s.holdings[0].name='Front';s.entries[0].name='Front';s.matches['cmm:1']={status:'matched',card_id:'c'};const c={id:'c',oracle_id:'o',name:'Front // Back',set:'cmm',collector_number:'1',card_faces:[{name:'Front'},{name:'Back'}],prices:{eur:'2.30',eur_foil:'4.50',usd:null}};let inv=new Inventory(s,[c]);assert.equal(inv.collection()[0].name,'Front // Back');assert.equal(inv.collection()[0].value,2.3);assert.equal(inv.deck(1).covered,1);s.holdings[0].finish='foil';assert.equal(new Inventory(s,[c]).collection()[0].value,4.5);s.settings.currency='USD';assert.equal(new Inventory(s,[c]).collection()[0].value,null);});
test('Deck zones, exact-edition syntax, exports and bad lines',()=>{const es=parseDecklist('Commander\n1 Ramos, Dragon Engine\nDeck\n4 Lightning Bolt (M11) 001\nSideboard\n2 Mountain');assert.equal(es[0].zone,'commander');assert.equal(es[1].printing_key,'m11:1');assert.equal(es[2].zone,'sideboard');assert.throws(()=>parseDecklist('0 Sol Ring'));assert.equal(textExport(new Inventory(initial()).collection()).trim().split('\n').reduce((a,line)=>a+Number(line.split(' ')[0]),0),seed.copies);});
test('Deleting a seeded deck prevents it returning on import',()=>{const s=initial();const before=s.decks.length;const id=s.decks[0].id;s.decks=s.decks.filter(d=>d.id!==id);s.entries=s.entries.filter(e=>e.deck_id!==id);applySnapshot(s,seed,'again');assert.equal(s.decks.length,before-1);});
