"""Focused Review navigation, plain layouts, and failure/revision guards. Browser-local fixtures only."""
import argparse,copy,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser();parser.add_argument('--url',default='http://127.0.0.1:4182');args=parser.parse_args();shots=Path('/tmp/mtg-review-qa');shots.mkdir(exist_ok=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage']);page=browser.new_page(viewport={'width':1366,'height':768});page.set_default_timeout(10000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto(args.url+'/#review');page.get_by_role('heading',name='Review',exact=True).wait_for();state=page.request.get(args.url+'/api/state').json();owned=state['summary']['copies'];issues=page.request.get(args.url+'/api/issues').json();nav=page.get_by_role('navigation',name='Main navigation');main=page.locator('main')
 def bounds(label):
  d=page.evaluate('({h:innerHeight,w:innerWidth,dh:document.documentElement.scrollHeight,dw:document.documentElement.scrollWidth,mw:document.querySelector("main").scrollWidth,mc:document.querySelector("main").clientWidth})');assert d['dh']<=d['h']+1 and d['dw']<=d['w'] and d['mw']<=d['mc']+1,(label,d)
 for theme in ['light','dark']:
  nav.get_by_role('button',name='Settings',exact=True).click();page.get_by_role('tab',name='Preferences',exact=True).click();page.get_by_role('group',name='Appearance').get_by_role('button',name=theme.title(),exact=True).click()
  for width,height in [(1366,768),(1024,768),(820,700),(390,844),(360,640)]:
   page.set_viewport_size({'width':width,'height':height});nav.get_by_role('button',name='Review',exact=True).click();expect(page.get_by_role('heading',name='Workbook issues',exact=False)).to_be_visible();assert not page.locator('.review-history').evaluate('e=>e.open');bounds((theme,width,'workbook'));page.screenshot(path=str(shots/f'workbook-{theme}-{width}.png'))
   page.get_by_role('navigation',name='Review views').get_by_role('link',name='Matching',exact=True).click();page.locator('.match-row').first.wait_for();bounds((theme,width,'matching'));assert page.locator('.match-row').first.bounding_box()['y']<height-90;page.screenshot(path=str(shots/f'matching-{theme}-{width}.png'));assert nav.get_by_role('button').count()==4;assert page.evaluate('document.documentElement.dataset.theme')==theme
 page.set_viewport_size({'width':1366,'height':768});page.get_by_role('button',name='Next matching page',exact=True).click();expect(page.get_by_role('region',name='Printing matches, page 2 of',exact=False)).to_be_focused()
 page.get_by_label('Search unresolved printings').fill('Sol Ring');assert 'q=Sol+Ring' in page.url;page.reload();expect(page.get_by_label('Search unresolved printings')).to_have_value('Sol Ring');page.get_by_role('navigation',name='Review views').get_by_role('link',name='Workbook',exact=True).click();page.go_back();expect(page.get_by_label('Search unresolved printings')).to_have_value('Sol Ring')
 # A loaded state is distinct from failed/not-yet-loaded source review.
 held=[];page.route('**/api/issues',lambda r:held.append(r));page.goto(args.url+'/#review');page.reload();page.get_by_role('status').filter(has_text='Loading review').wait_for();assert page.get_by_role('heading',name='Workbook issues',exact=False).count()==0;page.wait_for_timeout(100);[r.fulfill(status=503,content_type='application/json',body='{"detail":"Controlled review failure"}') for r in held];held.clear();page.get_by_role('alert').filter(has_text='Controlled review failure').wait_for();page.get_by_role('button',name='Retry review',exact=True).click();page.wait_for_timeout(100);assert held;[r.fulfill(content_type='application/json',body=json.dumps(issues)) for r in held];page.unroute('**/api/issues');page.get_by_role('heading',name='Workbook issues',exact=False).wait_for()
 # Upload routes straight to Workbook; search does not alter the complete snapshot apply request.
 fixture=copy.deepcopy(state);fixture['pending_import']={'id':'qa-browser-snapshot','source':'Browser fixture.xlsx','before_copies':owned,'copies':owned+1,'rows':679,'reductions':[],'changes':[{'name':'Snapshot card '+str(i),'printing_key':'abc#'+str(i),'kind':'Added','finish':'nonfoil','before':0,'after':1,'source_rows':[i+2]} for i in range(22)],'issues':[],'affected_decks':[]}
 page.route('**/api/state',lambda r:r.fulfill(content_type='application/json',body=json.dumps(fixture)));page.route('**/api/upload',lambda r:r.fulfill(content_type='application/json',body='{"staged":true}'));page.get_by_role('navigation',name='Review views').get_by_role('link',name='Matching',exact=True).click();page.locator('input[type=file]').set_input_files({'name':'Browser fixture.xlsx','mimeType':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','buffer':b'local controlled upload'});page.get_by_label('Search snapshot changes').wait_for();assert 'view=matching' not in page.url;expect(page.get_by_role('navigation',name='Review views').get_by_role('link',name='Workbook',exact=True)).to_have_attribute('aria-current','page')
 for width,height in [(1366,768),(820,700),(360,640)]:
  page.set_viewport_size({'width':width,'height':height});bounds(('snapshot',width));page.screenshot(path=str(shots/f'snapshot-{width}.png'))
 page.get_by_label('Search snapshot changes').fill('Snapshot card 21');assert page.locator('.review-changes tbody tr').count()==1;applies=[]
 def reject_apply(r):applies.append(r.request.post_data);r.fulfill(status=503,content_type='application/json',body='{"detail":"Controlled apply rejection"}')
 page.route('**/api/import/qa-browser-snapshot/apply',reject_apply);page.get_by_role('button',name='Apply complete snapshot',exact=True).click();page.get_by_role('alert').filter(has_text='Controlled apply rejection').wait_for();assert applies==[None];page.get_by_label('Search snapshot changes').fill('');assert page.locator('.review-changes tbody tr').count()==20;page.get_by_role('button',name='Apply complete snapshot',exact=True).click();alert=page.get_by_role('alert').filter(has_text='Controlled apply rejection');expect(alert).to_be_focused();box=alert.bounding_box();assert box['y']>=main.bounding_box()['y'] and box['y']+box['height']<=page.viewport_size['height'];assert page.get_by_label('Search snapshot changes').count()==1;assert applies==[None,None];page.unroute('**/api/import/qa-browser-snapshot/apply');page.unroute('**/api/upload');page.unroute('**/api/state')
 # Dialog confirmation must retain its opening revision across the normal background refresh.
 page.set_viewport_size({'width':1366,'height':768});page.goto(args.url+'/#review?view=matching');page.reload();page.locator('.match-row').first.wait_for();opening=page.request.get(args.url+'/api/state').json()['revision'];page.get_by_role('button',name='Find printing',exact=True).first.click();dialog=page.get_by_role('dialog',name='Confirm a printing');dialog.wait_for();newer=copy.deepcopy(state);newer['revision']=opening+1;page.route('**/api/state',lambda r:r.fulfill(content_type='application/json',body=json.dumps(newer)));page.wait_for_timeout(16000)
 card={'id':'qa-match-card','name':'Controlled printing','set':'abc','set_name':'Example edition','collector_number':'1','type_line':'Creature','mana_cost':'','oracle_text':'','image_uris':{},'card_faces':[]};page.route('**/api/cards/search**',lambda r:r.fulfill(content_type='application/json',body=json.dumps([card])));dialog.get_by_role('button',name='Search',exact=True).click();dialog.get_by_role('button',name='Controlled printing',exact=False).wait_for();confirm=[]
 def reject_confirm(r):confirm.append(r.request.headers['x-vault-revision']);r.fulfill(status=409,content_type='application/json',body='{"detail":"The vault changed in another tab. Close and reopen this printing before confirming."}')
 page.route('**/api/matches/confirm',reject_confirm);dialog.get_by_role('button',name='Controlled printing',exact=False).click();expect(dialog.get_by_role('alert')).to_contain_text('another tab');assert confirm==[str(opening)],confirm;page.keyboard.press('Escape');page.unroute('**/api/state');page.unroute('**/api/cards/search**');page.unroute('**/api/matches/confirm')
 page.goto(args.url+'/#settings?section=data&review=1');page.get_by_role('heading',name='Review',exact=True).wait_for();assert '#review?view=workbook' in page.url;nav.get_by_role('button',name='Settings',exact=True).click();page.get_by_role('tab',name='Data & prices',exact=True).click();page.get_by_role('link',name='Review matches',exact=True).click();page.get_by_label('Search unresolved printings').wait_for();assert 'view=matching' in page.url
 page.set_viewport_size({'width':700,'height':1000});page.evaluate("document.documentElement.style.fontSize='32px'");bounds('matching 200%');page.get_by_role('navigation',name='Review views').get_by_role('link',name='Workbook',exact=True).click();bounds('workbook 200%');assert page.request.get(args.url+'/api/state').json()['summary']['copies']==owned;assert not errors,errors;browser.close()
print('Passed four-section Review layouts/two themes, mobile snapshot rows, precise links, history disclosure, pagination focus, query reload/Back, loading/failure/Retry, staged upload to Workbook, complete filtered-snapshot apply, captured matching revision through background refresh, and 200% text. No inventory writes or browser errors.')
