"""Four-section working UI regression against disposable local storage; long-content/save fixtures stay browser-local."""
import argparse,copy,json
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
parser=argparse.ArgumentParser();parser.add_argument('--url',default='http://127.0.0.1:4182');args=parser.parse_args();shots=Path('/tmp/mtg-simple-qa');shots.mkdir(exist_ok=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--disable-dev-shm-usage']);page=browser.new_page(viewport={'width':1366,'height':768});page.set_default_timeout(10000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto(args.url);page.get_by_role('heading',name='Collection',exact=True).wait_for();state=page.request.get(args.url+'/api/state').json();owned=state['summary']['copies'];nav=page.get_by_role('navigation',name='Main navigation');main=page.locator('main')
 def go(name):nav.get_by_role('button',name=name,exact=True).click();page.wait_for_timeout(50)
 def bounds(label):
  d=page.evaluate("({height:innerHeight,doc:document.documentElement.scrollHeight,width:innerWidth,docWidth:document.documentElement.scrollWidth,main:document.querySelector('main').scrollWidth,client:document.querySelector('main').clientWidth})")
  assert d['doc']<=d['height']+1 and d['docWidth']<=d['width'] and d['main']<=d['client']+1,(label,d)
  main.evaluate('e=>e.scrollTop=e.scrollHeight');assert page.evaluate('scrollY')==0;main.evaluate('e=>e.scrollTop=0')
 for mode in ['light','dark']:
  go('Settings');page.get_by_role('tab',name='Preferences',exact=True).click();page.get_by_role('group',name='Appearance').get_by_role('button',name=mode.title(),exact=True).click()
  for width,height in [(1366,768),(1280,720),(1024,768),(820,700),(701,700),(700,700),(390,844),(360,640)]:
   page.set_viewport_size({'width':width,'height':height});assert nav.get_by_role('button').count()==4
   go('Collection');bounds((mode,width,'collection'));page.screenshot(path=str(shots/f'collection-{mode}-{width}.png'))
   table=page.locator('.desktop-collection');rows=page.locator('.mobile-card-list')
   if table.is_visible():assert table.evaluate('e=>e.scrollWidth<=e.clientWidth+1')
   else:assert rows.is_visible();assert page.locator('.mobile-card-row').first.bounding_box()['y']<480
   go('Decks');bounds((mode,width,'library'));page.screenshot(path=str(shots/f'library-{mode}-{width}.png'));page.locator('.deck-library-row').first.click();bounds((mode,width,'deck'));assert page.locator('.deck-card-entry').first.bounding_box()['y']<480;page.screenshot(path=str(shots/f'deck-{mode}-{width}.png'))
   page.get_by_role('button',name='Edit list',exact=True).click();editor=page.get_by_role('region',name='Deck editor');editor.wait_for();bounds((mode,width,'editor'));first=editor.get_by_label('Card name 1',exact=True);assert first.bounding_box()['y']<height-70;assert editor.get_by_role('button',name='Save deck',exact=True).bounding_box()['y']<height;assert first.evaluate("e=>!!(document.querySelector('.editor-paste').compareDocumentPosition(e)&4)");page.screenshot(path=str(shots/f'editor-{mode}-{width}.png'));go('Decks');page.get_by_role('heading',name='Decks',exact=True).wait_for();assert page.get_by_role('region',name='Deck editor').count()==0
   go('Settings');bounds((mode,width,'settings'));assert page.evaluate('document.documentElement.dataset.theme')==mode;page.screenshot(path=str(shots/f'settings-{mode}-{width}.png'))
 page.set_viewport_size({'width':1366,'height':768});go('Collection');comfortable=page.locator('tbody tr').first.bounding_box()['height'];page.get_by_role('button',name='Display',exact=True).click();display=page.get_by_role('dialog',name='Collection display');display.get_by_label('Row density').select_option('compact');display.get_by_role('button',name='Done',exact=True).click();compact=page.locator('tbody tr').first.bounding_box()['height'];assert compact<comfortable-8,(comfortable,compact)
 page.locator('tbody tr .printing-select input').last.check();expect(page.get_by_role('checkbox',name='Select current page',exact=True)).to_have_js_property('indeterminate',True);actions=page.get_by_role('button',name='Actions',exact=True);assert actions.bounding_box()['y']>=main.bounding_box()['y'] and actions.bounding_box()['y']<main.bounding_box()['y']+200
 main.evaluate('e=>e.scrollTop=e.scrollHeight');page.get_by_role('button',name='Next page',exact=True).click();expect(page.get_by_role('region',name='Collection results, page 2 of 22')).to_be_focused();assert page.locator('tbody tr').first.bounding_box()['y']>=page.locator('.collection-controls').bounding_box()['y'];assert page.locator('tbody tr').first.bounding_box()['y']<main.bounding_box()['y']+220
 page.get_by_role('button',name='Clear selection',exact=True).click();page.get_by_role('button',name='Display',exact=True).click();display=page.get_by_role('dialog',name='Collection display');display.get_by_label('Row density').select_option('comfortable');display.get_by_role('checkbox',name='Excel Deck labels',exact=True).check();display.get_by_role('checkbox',name='Reservations',exact=True).check();display.get_by_role('button',name='Done',exact=True).click();assert page.locator('.desktop-collection').evaluate('e=>e.scrollWidth<=e.clientWidth+1')
 # Long chips and names are browser-local fixtures, never saved to inventory.
 page.set_viewport_size({'width':360,'height':640});page.evaluate("location.hash='collection?q='+encodeURIComponent('Q'.repeat(180))+'&location='+encodeURIComponent('L'.repeat(180))+'&sets=abc,def,ghi,jkl,mno,pqr'");page.get_by_role('button',name='Remove Sets filter',exact=True).wait_for();bounds('long active chips');assert '6 sets' in page.get_by_role('button',name='Remove Sets filter',exact=True).inner_text();page.get_by_role('button',name='Clear filters',exact=True).first.click()
 cards=page.request.get(args.url+'/api/collection').json();longcards=copy.deepcopy(cards);longcards[0]['name']='LongPrintingName'*20;page.route('**/api/collection',lambda r:r.fulfill(content_type='application/json',body=json.dumps(longcards)));page.reload();page.locator('.mobile-card-row').first.wait_for();bounds('long name mobile');page.set_viewport_size({'width':1366,'height':768});bounds('long name desktop');assert page.locator('.desktop-collection').evaluate('e=>e.scrollWidth<=e.clientWidth+1');page.unroute('**/api/collection')
 # Long deck and intercepted saves verify editing reachability, dirty guards, and pending/rejected writes.
 fixture=copy.deepcopy(state);deck=fixture['decks'][0];base=copy.deepcopy(deck['entries'][0]);deck['entries']=[{**base,'id':10000+i,'name':'QA long card '+str(i+1),'quantity':1,'card':None} for i in range(100)];deck['total']=100;deck['readiness']['list'].update(entered=100,complete=False,unspecified=0)
 page.route('**/api/state',lambda r:r.fulfill(content_type='application/json',body=json.dumps(fixture)));page.goto(args.url+'/#decks?deck='+str(deck['id'])+'&edit=1');page.reload();editor=page.get_by_role('region',name='Deck editor');editor.get_by_label('Card name 1',exact=True).wait_for();editor.get_by_role('button',name='Add card row',exact=True).click();expect(editor.get_by_label('Card name 101',exact=True)).to_be_focused();assert editor.get_by_label('Card name 101',exact=True).bounding_box()['y']<768-70;validation=[];page.route('**/api/decks/validate',lambda r:validation.append(r));editor.get_by_label('Card name 101',exact=True).fill('QA new draft card');page.wait_for_timeout(450)
 go('Settings');guard=page.get_by_role('dialog',name='Unsaved deck changes');guard.wait_for();guard.get_by_role('button',name='Continue editing',exact=True).click();expect(editor.get_by_label('Card name 101',exact=True)).to_have_value('QA new draft card');assert 'edit=1' in page.url
 held=[]
 def hold_save(route):
  if route.request.method=='PUT':held.append(route)
  else:route.continue_()
 page.route('**/api/decks/'+str(deck['id']),hold_save);editor.get_by_role('button',name='Save deck',exact=True).click();page.wait_for_timeout(100);assert held;expect(editor.get_by_label('Card name 101',exact=True)).to_be_disabled();go('Collection');assert editor.is_visible() and 'edit=1' in page.url;held.pop().fulfill(status=503,content_type='application/json',body='{"detail":"Controlled save rejection"}');alert=editor.get_by_role('alert').filter(has_text='Controlled save rejection');alert.wait_for();assert alert.bounding_box()['y']>=main.bounding_box()['y'] and alert.bounding_box()['y']<768-50;assert validation;[r.fulfill(content_type='application/json',body=json.dumps(deck)) for r in validation];page.wait_for_timeout(100);expect(alert).to_be_visible();page.unroute('**/api/decks/validate');expect(editor.get_by_label('Card name 101',exact=True)).to_be_enabled();expect(editor.get_by_label('Card name 101',exact=True)).to_have_value('QA new draft card');editor.get_by_role('button',name='Cancel',exact=True).click();page.get_by_role('dialog',name='Unsaved deck changes').get_by_role('button',name='Discard changes',exact=True).click()
 page.goto(args.url+'/#decks?deck='+str(deck['id'])+'&edit=1');editor=page.get_by_role('region',name='Deck editor');editor.get_by_label('Card name 1',exact=True).wait_for();editor.get_by_role('button',name='Save deck',exact=True).click();page.wait_for_timeout(100);assert held;go('Settings');assert editor.is_visible();expect(editor.get_by_label('Card name 1',exact=True)).to_be_disabled();held.pop().fulfill(status=503,content_type='application/json',body='{"detail":"Controlled unchanged save rejection"}');editor.get_by_role('alert').filter(has_text='Controlled unchanged').wait_for();editor.get_by_role('button',name='Cancel',exact=True).click()
 page.unroute('**/api/state');page.unroute('**/api/decks/'+str(deck['id']));page.goto(args.url+'/#review');page.get_by_role('heading',name='Review',exact=True).wait_for();assert '#review' in page.url;page.goto(args.url+'/#missing');page.get_by_role('heading',name='Compare decks',exact=True).wait_for();assert '#decks?view=missing' in page.url
 page.goto(args.url+'/#overview');page.get_by_role('heading',name='Collection',exact=True).wait_for();assert '#collection' in page.url
 assert page.request.get(args.url+'/api/state').json()['summary']['copies']==owned;assert not errors,errors;browser.close()
print('Passed four-section navigation, 8 widths/two actual themes, early deck rows, inline editor/mobile order, compact density, mixed selection/sticky Actions, pagination focus/start, all columns, long chips/names, 100-card Add focus, dirty/busy guards, disabled editing during rejected save, legacy aliases; no inventory writes or browser errors.')
