export const normalized = s => String(s??'').normalize('NFKC').replaceAll('’',"'").toLowerCase().trim().replace(/\s+/g,' ');
export const collector = s => /^\d+$/.test(String(s)) ? String(Number(s)) : String(s??'').trim();
export const printingKey=(s,n)=>`${String(s??'').trim().toLowerCase()}:${collector(n)}`;
export function parseDecklist(text){
 const grouped=new Map();let zone='main';
 for(const [i,raw] of String(text).split('\n').entries()){
  let line=raw.trim();if(!line)continue;
  const head=line.replace(/^\/\//,'').replace(/^[\[:]+|[\]:]+$/g,'').trim().toLowerCase();
  if(['commander','commanders','command zone','sideboard','main','mainboard','deck','maindeck'].includes(head)){zone=head.startsWith('command')?'commander':head==='sideboard'?'sideboard':'main';continue;}
  if(line.startsWith('#')||line.startsWith('//'))continue;
  const m=line.match(/^(\d+)\s*x?\s+(.+)$/i);if(!m||Number(m[1])<1||Number(m[1])>100000)throw Error(`Line ${i+1}: use a positive quantity followed by a card name.`);
  let name=m[2].trim(),key=null;const exact=name.match(/^(.+?)\s+\(([A-Za-z0-9]{2,8})\)\s+([0-9]+[A-Za-z★]*)$/);
  if(exact){name=exact[1].trim();key=printingKey(exact[2],exact[3]);}
  const k=JSON.stringify([normalized(name),zone,key]);const e=grouped.get(k)||{name,zone,printing_key:key,quantity:0};e.quantity+=Number(m[1]);grouped.set(k,e);
 }
 return [...grouped.values()];
}
export const freshState=()=>({settings:{workbook_path:'MagicTheGatheringInventory.xlsx',currency:'EUR',auto_watch:false,foil_mode:'total',last_import_error:'',last_price_success:null},holdings:[],issues:[],matches:{},decks:[],entries:[],seeded_labels:[],history:[],pending_import:null,price_job:{running:false,completed:0,total:0,error:'',message:''}});
export function counts(holdings){const out={};for(const h of holdings){const k=JSON.stringify([h.printing_key,h.finish,normalized(h.name)]);out[k]=(out[k]||0)+h.quantity;}return out;}
export function reductions(old,next){const a=counts(old),b=counts(next);return Object.entries(a).filter(([k,n])=>(b[k]||0)<n).map(([k,n])=>{const [printing_key,finish,name]=JSON.parse(k);return {name,printing_key,finish,before:n,after:b[k]||0};});}
export function applySnapshot(s,p,id){
 s.holdings=p.holdings.map((h,i)=>({...h,id:i+1}));s.issues=p.issues.map((r,i)=>({...r,id:i+1}));
 for(const h of s.holdings)s.matches[h.printing_key]??={status:'unresolved',message:'',card_id:null};
 const labels=new Map();for(const h of s.holdings){if(!h.deck_label)continue;const group=labels.get(h.deck_label)||new Map();group.set(h.name,(group.get(h.name)||0)+h.quantity);labels.set(h.deck_label,group);}
 for(const [label,group]of labels){if(s.seeded_labels.includes(label))continue;const did=Math.max(0,...s.decks.map(d=>d.id))+1;s.decks.push({id:did,name:label,format:label.toLowerCase().includes('commander')?'commander':'casual60',active:1,priority:0,source_label:label,seeded:1,updated_at:new Date().toISOString()});for(const [name,quantity]of group)s.entries.push({id:Math.max(0,...s.entries.map(e=>e.id))+1,deck_id:did,name,quantity,zone:'main',printing_key:null});s.seeded_labels.push(label);}
 s.settings.workbook_path=p.source;s.settings.last_import_error='';s.pending_import=null;s.fingerprint=p.fingerprint;s.last_import={id,source:p.source,created_at:new Date().toISOString()};
}
export class Inventory{
 constructor(s,cards=[]){this.s=s;this.cards=new Map(cards.map(c=>[c.id,c]));this.names=new Map();for(const c of cards)for(const name of [c.name,...(c.card_faces||[]).map(f=>f.name)])this.names.set(normalized(name),c);this.holdings=s.holdings.map(h=>({...h,identity:this.identity(h.name,this.card(h.printing_key))}));this.entries=s.entries.map(e=>{const card=e.printing_key?this.card(e.printing_key):this.names.get(normalized(e.name));return {...e,identity:this.identity(e.name,card),card,canonical_name:card?.name||e.name};});this.decks=s.decks;}
 card(key){const m=this.s.matches[key];return m?.status==='matched'?this.cards.get(m.card_id):null;}
 identity(name,card){card??=this.names.get(normalized(name));return card?.oracle_id?`oracle:${card.oracle_id}`:`name:${normalized(card?.name||name)}`;}
 effective(key){const c=this.card(key);return c?printingKey(c.set,c.collector_number):key;}
 compatible(e,h){return e.identity===h.identity&&(!e.printing_key||this.effective(e.printing_key)===this.effective(h.printing_key));}
 unit(h){const c=this.card(h.printing_key);const k=(this.s.settings.currency==='EUR'?'eur':'usd')+(h.finish==='foil'?'_foil':'');const raw=c?.prices?.[k];return raw!=null&&raw!==''&&Number.isFinite(Number(raw))&&Number(raw)>=0?Number(raw):null;}
 estimate(e){const prices=this.holdings.filter(h=>this.compatible(e,h)).map(h=>this.unit(h));if(e.card)for(const k of this.s.settings.currency==='EUR'?['eur','eur_foil']:['usd','usd_foil','usd_etched']){const n=e.card.prices?.[k];if(n!=null&&n!==''&&Number.isFinite(Number(n)))prices.push(Number(n));}const known=prices.filter(n=>n!==null&&n>=0);return known.length?Math.min(...known):null;}
 allocate(ids){const remaining=new Map(this.holdings.map(h=>[h.id,h.quantity])),out=new Map();const entries=this.entries.filter(e=>ids.has(e.deck_id)).sort((a,b)=>Number(!a.printing_key)-Number(!b.printing_key)||(this.decks.find(d=>d.id===a.deck_id)?.priority||0)-(this.decks.find(d=>d.id===b.deck_id)?.priority||0)||a.deck_id-b.deck_id||a.id-b.id);for(const e of entries){let need=e.quantity;const d=this.decks.find(d=>d.id===e.deck_id);const holdings=this.holdings.filter(h=>this.compatible(e,h)).sort((a,b)=>Number(a.deck_label!==(d.source_label||d.name))-Number(b.deck_label!==(d.source_label||d.name))||a.id-b.id);const pairs=[];for(const h of holdings){const take=Math.min(need,remaining.get(h.id));if(take){pairs.push([h.id,take]);remaining.set(h.id,remaining.get(h.id)-take);need-=take;}if(!need)break;}out.set(e.id,pairs);}return out;}
 collection(){const groups=new Map();for(const h of this.holdings){const key=`${h.printing_key}|${normalized(h.name)}`,c=this.card(h.printing_key),m=this.s.matches[h.printing_key];let row=groups.get(key);if(!row){row={key,printing_key:h.printing_key,name:c?.name||h.name,set_code:h.set_code,collector_number:h.collector_number,quantity:0,nonfoil:0,foil:0,card_type:c?.type_line||h.card_type,color:h.color,rarity:h.rarity,value:0,priced_copies:0,prices:{nonfoil:null,foil:null},decks:[],notes:[],source_rows:[],match_status:m?.status||'unresolved',match_message:m?.message||'',image_url:c?.image_uris?.normal||c?.card_faces?.find(f=>f.image_uris)?.image_uris?.normal||null,scryfall_url:c?.scryfall_uri||null,oracle_text:c?.oracle_text||(c?.card_faces||[]).map(f=>f.oracle_text||'').join('\n\n'),mana_cost:c?.mana_cost||'',fetched_at:c?.fetched_at||null};groups.set(key,row);}row.quantity+=h.quantity;row[h.finish]+=h.quantity;const price=this.unit(h);if(price!==null){row.prices[h.finish]=price;row.value+=Math.round(price*100)*h.quantity/100;row.priced_copies+=h.quantity;}for(const [k,v]of [['decks',h.deck_label],['notes',h.notes],['source_rows',h.source_row]])if(v&&!row[k].includes(v))row[k].push(v);}return [...groups.values()].map(c=>({...c,value:c.priced_copies?Math.round(c.value*100)/100:null})).sort((a,b)=>a.name.localeCompare(b.name));}
 warnings(d,entries){const out=[],total=entries.filter(e=>e.zone!=='sideboard').reduce((a,e)=>a+e.quantity,0);if(d.seeded)out.push('Started from workbook assignments. Save the intended target list, including cards you do not own.');if(d.format==='commander'){if(total!==100)out.push(`This list contains ${total} cards outside the sideboard; a typical Commander deck has 100.`);const cmd=entries.filter(e=>e.zone==='commander');if(!cmd.length)out.push('No commander is designated. Add a Commander section.');if(cmd.reduce((a,e)=>a+e.quantity,0)>1)out.push('Review multiple-commander pairing rules manually.');if(cmd.length&&cmd.every(e=>e.card)){const colors=new Set(cmd.flatMap(e=>e.card.color_identity||[]));const outside=entries.filter(e=>e.card&&(e.card.color_identity||[]).some(c=>!colors.has(c)));if(outside.length)out.push('Outside commander color identity: '+outside.map(e=>e.canonical_name).join(', '));}}else if(total<60)out.push(`Main deck has ${total} cards; a typical 60-card format requires at least 60.`);const groups=new Map();for(const e of entries){const g=groups.get(e.identity)||[];g.push(e);groups.set(e.identity,g);}for(const group of groups.values()){const e=group[0],c=e.card,n=group.reduce((a,x)=>a+x.quantity,0);const basic=/Basic.*Land/.test(c?.type_line||'')||/^(Snow-Covered )?(Plains|Island|Swamp|Mountain|Forest|Wastes)$/.test(e.name);const limit=d.format==='commander'?1:4;if(n>limit&&!basic&&!/a deck can have (any number|up to)/i.test(c?.oracle_text||''))out.push(`${e.canonical_name}: ${n} copies exceed the usual ${limit}-copy limit. Check card-specific exceptions.`);const legal=c?.legalities?.[d.format];if(d.format!=='casual60'&&['banned','not_legal'].includes(legal))out.push(`${e.canonical_name} is ${legal.replace('_',' ')} in ${d.format}.`);if(legal==='restricted'&&n>1)out.push(`${e.canonical_name} is restricted to one copy.`);}const unknown=entries.filter(e=>!e.card).reduce((a,e)=>a+e.quantity,0);if(unknown)out.push(`Rules and legality metadata are unavailable for ${unknown} copies. Format checks are incomplete.`);return out;}
 deck(id){const d=this.decks.find(d=>d.id===id);if(!d)throw Error('Deck not found.');const entries=this.entries.filter(e=>e.deck_id===id),own=this.allocate(new Set([id])),allocated=this.allocate(new Set([...this.decks.filter(d=>d.active).map(d=>d.id),id])),elsewhere=new Map();for(const e of this.entries)if(e.deck_id!==id)for(const [hid,n]of allocated.get(e.id)||[])elsewhere.set(hid,(elsewhere.get(hid)||0)+n);const rows=entries.map(e=>{const holdings=this.holdings.filter(h=>this.compatible(e,h)),owned=holdings.reduce((a,h)=>a+h.quantity,0),other=holdings.reduce((a,h)=>a+(elsewhere.get(h.id)||0),0),covered=(own.get(e.id)||[]).reduce((a,p)=>a+p[1],0),assigned=(allocated.get(e.id)||[]).reduce((a,p)=>a+p[1],0);return {id:e.id,name:e.canonical_name,quantity:e.quantity,zone:e.zone,printing_key:e.printing_key,owned,available:owned-other,in_other_decks:other,covered,assigned,missing:e.quantity-covered,missing_now:e.quantity-assigned,estimate:this.estimate(e)};});const list=[];for(const zone of ['commander','main','sideboard']){const es=entries.filter(e=>e.zone===zone);if(!es.length)continue;if(list.length)list.push('');list.push({commander:'Commander',main:'Deck',sideboard:'Sideboard'}[zone]);for(const e of es)list.push(`${e.quantity} ${e.name}${e.printing_key?' ('+e.printing_key.split(':')[0].toUpperCase()+') '+e.printing_key.split(':')[1]:''}`);}return {...d,entries:rows,decklist:list.join('\n'),warnings:this.warnings(d,entries),total:rows.reduce((a,e)=>a+e.quantity,0),covered:rows.reduce((a,e)=>a+e.covered,0),missing:rows.reduce((a,e)=>a+e.missing,0),missing_now:rows.reduce((a,e)=>a+e.missing_now,0)};}
 wishlist(ids,mode='assembled'){if(!['assembled','shared'].includes(mode))throw Error('Choose assembled or shared decks.');const entries=this.entries.filter(e=>ids.has(e.deck_id)),items=[];const push=(e,quantity,dids)=>{if(quantity>0)items.push({name:e.canonical_name,printing_key:e.printing_key,quantity,estimate:this.estimate(e),decks:[...dids].map(id=>this.decks.find(d=>d.id===id)?.name||'')});};if(mode==='assembled'){const a=this.allocate(ids),groups=new Map();for(const e of entries){const n=e.quantity-(a.get(e.id)||[]).reduce((a,p)=>a+p[1],0);if(!n)continue;const key=JSON.stringify([e.identity,e.printing_key]),g=groups.get(key)||{e,n:0,ids:new Set()};g.n+=n;g.ids.add(e.deck_id);groups.set(key,g);}for(const g of groups.values())push(g.e,g.n,g.ids);}else{const groups=new Map();for(const e of entries){const g=groups.get(e.identity)||[];g.push(e);groups.set(e.identity,g);}for(const [identity,group]of groups){const totals=new Map(),exact=new Map(),owned=new Map();for(const e of group){totals.set(e.deck_id,(totals.get(e.deck_id)||0)+e.quantity);if(e.printing_key){const k=this.effective(e.printing_key),g=exact.get(k)||new Map();g.set(e.deck_id,(g.get(e.deck_id)||0)+e.quantity);exact.set(k,g);}}for(const h of this.holdings.filter(h=>h.identity===identity)){const k=this.effective(h.printing_key);owned.set(k,(owned.get(k)||0)+h.quantity);}let shortages=0;for(const [k,demands]of exact){const n=Math.max(0,Math.max(...demands.values())-(owned.get(k)||0));shortages+=n;push(group.find(e=>e.printing_key&&this.effective(e.printing_key)===k),n,new Set(demands.keys()));}const extra=Math.max(0,Math.max(...totals.values())-[...owned.values()].reduce((a,n)=>a+n,0)-shortages);push({...group.find(e=>!e.printing_key)||group[0],printing_key:null},extra,new Set(totals.keys()));}}return {items:items.sort((a,b)=>a.name.localeCompare(b.name)),copies:items.reduce((a,e)=>a+e.quantity,0),estimate:items.reduce((a,e)=>a+(e.estimate??0)*e.quantity,0),priced_copies:items.filter(e=>e.estimate!==null).reduce((a,e)=>a+e.quantity,0),mode};}
}
export function textExport(rows){const map=new Map();for(const r of rows)if(r.quantity>0)map.set(r.name,(map.get(r.name)||0)+r.quantity);return [...map].sort((a,b)=>a[0].localeCompare(b[0])).map(([name,n])=>`${n} ${name}`).join('\n')+(map.size?'\n':'');}
