import {Inventory,freshState,applySnapshot,reductions,parseDecklist,textExport,printingKey,normalized} from './domain.mjs';
import {parseWorkbook,MAX_BYTES} from './importer.mjs';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const now=()=>new Date().toISOString();
const formats=new Set(['commander','casual60','standard','modern','pioneer','legacy','vintage','pauper']);
async function load(env){
 if(!env.DB)throw Error('Collection storage is unavailable. Please try again.');
 let row=await env.DB.prepare('SELECT revision,payload FROM vault WHERE id=1').first();
 if(!row){const state=freshState();state.settings.workbook_path='No workbook uploaded';state.price_job={...state.price_job,attempted_at:now()};await env.DB.prepare('INSERT OR IGNORE INTO vault (id,revision,payload) VALUES (1,0,?)').bind(JSON.stringify(state)).run();row=await env.DB.prepare('SELECT revision,payload FROM vault WHERE id=1').first();}
 const s=JSON.parse(row.payload);
 // Optional private bootstrap data is a runtime secret, never source or browser data.
 const initialSnapshot=env.INITIAL_INVENTORY_SNAPSHOT||Array.from({length:16},(_,i)=>env['INITIAL_INVENTORY_SNAPSHOT_'+i]||'').join('');
 if(initialSnapshot&&!s.last_import&&!s.holdings.length){
  const bytes=Uint8Array.from(atob(initialSnapshot),c=>c.charCodeAt(0));
  const text=await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'))).text();
  if(text.length>1200000)throw Error('Initial inventory exceeds the supported snapshot size.');
  const p=JSON.parse(text);if(!Array.isArray(p.holdings)||!Array.isArray(p.issues)||typeof p.fingerprint!=='string')throw Error('Initial inventory snapshot is invalid.');
  const id='initial-'+p.fingerprint.slice(0,12);
  if(!env.BUCKET)throw Error('Workbook storage is unavailable.');
  await env.BUCKET.put('initial/import-snapshot.json',text,{httpMetadata:{contentType:'application/json'}});
  applySnapshot(s,p,id);s.history=[{id,created_at:s.last_import.created_at,source:p.source,status:'applied'}];
  await env.DB.prepare('INSERT OR IGNORE INTO imports (id,fingerprint,created_at,source,status,payload) VALUES (?,?,?,?,?,?)').bind(id,p.fingerprint,s.last_import.created_at,p.source,'initial',text).run();
  try {await save(env,s,row.revision);return {s,revision:row.revision+1};}
  catch(e){const latest=await env.DB.prepare('SELECT revision,payload FROM vault WHERE id=1').first();const accepted=JSON.parse(latest.payload);if(accepted.last_import)return {s:accepted,revision:latest.revision};throw e;}
 }
 return {s,revision:row.revision};
}
async function save(env,s,revision){const payload=JSON.stringify(s);if(new TextEncoder().encode(payload).length>1800000)throw Error('Collection storage is full. Download a backup and reduce the inventory size.');const r=await env.DB.prepare('UPDATE vault SET payload=?,revision=revision+1 WHERE id=1 AND revision=?').bind(payload,revision).run();if(!r.meta.changes)throw Error('The collection changed in another tab. Refresh and try again.');}
async function cardRows(env){const {results}=await env.DB.prepare('SELECT payload,fetched_at FROM cards').all();return results.map(r=>({...JSON.parse(r.payload),fetched_at:r.fetched_at}));}
async function putCards(env,cards){if(!cards.length)return;for(let i=0;i<cards.length;i+=50)await env.DB.batch(cards.slice(i,i+50).map(c=>env.DB.prepare('INSERT INTO cards (id,payload,fetched_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,fetched_at=excluded.fetched_at').bind(c.id,JSON.stringify(c),now())));}
async function backup(env,s){if(!env.BUCKET)throw Error('Workbook and backup storage is unavailable.');const cards=await cardRows(env);const payload=JSON.stringify({version:1,created_at:now(),state:s,cards});await env.BUCKET.put(`backups/${Date.now()}-${crypto.randomUUID()}.json`,payload,{httpMetadata:{contentType:'application/json'}});return payload;}
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function scryfall(path,options={}){for(let i=0;i<3;i++){let r;try { r=await fetch('https://api.scryfall.com'+path,{...options,headers:{Accept:'application/json','User-Agent':'MTG-Vault/1.0 (+https://github.com/pmerrild/mtg_collection)',...options.headers},signal:AbortSignal.timeout(12000)}); } catch {throw Error('Scryfall is unavailable. Cached card data and prices are retained.');} if(r.status===429||r.status>=500){if(i<2){await delay(400*(2**i));continue;}throw Error('Scryfall is temporarily unavailable. Cached data is retained.');}const data=await r.json();if(!r.ok)throw Error(data.details||'Scryfall lookup failed. Cached data is retained.');return data;}throw Error('Scryfall is unavailable.');}
function matchName(c,names){const aliases=new Set([c.name,...(c.card_faces||[]).map(f=>f.name)].map(normalized));return names.every(n=>aliases.has(normalized(n)));}
async function priceRefresh(env,force){
 let {s,revision}=await load(env);const cards=await cardRows(env),cardMap=new Map(cards.map(c=>[c.id,c]));const map=new Map();for(const h of [...s.holdings,...s.entries.filter(e=>e.printing_key)]){const names=map.get(h.printing_key)||[];names.push(h.name);map.set(h.printing_key,names);}const keys=[...map.keys()].filter(k=>{const m=s.matches[k],c=m&&cardMap.get(m.card_id);return force||!c||!c.fetched_at||Date.now()-new Date(c.fetched_at).getTime()>86400000;});
 const job={attempted_at:now(),running:true,completed:0,total:keys.length,error:'',message:'Refreshing Scryfall card data'};s.price_job=job;await save(env,s,revision);let completed=0;
 try{
  for(let i=0;i<keys.length;i+=75){const batch=keys.slice(i,i+75);const corrected=batch.filter(k=>s.matches[k]?.confirmed);const normal=batch.filter(k=>!s.matches[k]?.confirmed);let fetched=[];
   if(normal.length){const data=await scryfall('/cards/collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifiers:normal.map(k=>({set:k.split(':')[0],collector_number:k.split(':')[1]}))})});fetched.push(...data.data);}
   for(const k of corrected){await delay(210);fetched.push(await scryfall('/cards/'+s.matches[k].card_id));}
   await putCards(env,fetched);const latest=await load(env);const ns=latest.s;
   for(const k of batch){const c=ns.matches[k]?.confirmed?fetched.find(c=>c.id===ns.matches[k].card_id):fetched.find(c=>printingKey(c.set,c.collector_number)===k);if(!c){if(ns.matches[k]?.status!=='matched')ns.matches[k]={...ns.matches[k],status:'not_found',message:'Printing not found. Confirm the edition in Import review.'};}else if(ns.matches[k]?.confirmed||matchName(c,map.get(k))){ns.matches[k]={...ns.matches[k],status:'matched',card_id:c.id,message:'',checked_at:now()};}else if(ns.matches[k]?.status!=='matched'){ns.matches[k]={...ns.matches[k],status:'name_mismatch',candidate_id:c.id,message:`Scryfall returned ${c.name}. Confirm the printing before using its price.`};}}
   completed+=batch.length;ns.price_job={...job,completed};await save(env,ns,latest.revision);s=ns;await delay(210);
  }
  // Resolve unowned target names as well, for indicative acquisition costs and legality.
  const known=new Set((await cardRows(env)).flatMap(c=>[c.name,...(c.card_faces||[]).map(f=>f.name)].map(normalized)));const unknown=[...new Set(s.entries.filter(e=>!e.printing_key&&!known.has(normalized(e.name))).map(e=>e.name))];for(let i=0;i<unknown.length;i+=75){const data=await scryfall('/cards/collection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({identifiers:unknown.slice(i,i+75).map(name=>({name}))})});await putCards(env,data.data);await delay(210);}
  const latest=await load(env);latest.s.price_job={...job,running:false,completed:keys.length,message:'Card data refreshed'};latest.s.settings.last_price_success=now();await save(env,latest.s,latest.revision);
 }catch(e){const latest=await load(env);latest.s.price_job={...job,running:false,completed,error:e.message,message:'Cached data retained'};await save(env,latest.s,latest.revision);}
}
async function stage(env,s,revision,p,raw){if(p.fingerprint===s.fingerprint)return {unchanged:true,copies:p.copies,rows:p.rows,reductions:[]};if(!env.BUCKET)throw Error('Workbook storage is unavailable. Please try again.');const id=crypto.randomUUID(),changes=reductions(s.holdings,p.holdings);await env.BUCKET.put(`workbooks/${id}.xlsx`,raw,{httpMetadata:{contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}});await env.DB.prepare('INSERT INTO imports (id,fingerprint,created_at,source,status,payload) VALUES (?,?,?,?,?,?)').bind(id,p.fingerprint,now(),p.source,'staged',JSON.stringify(p)).run();s.history=s.history.filter(h=>h.id!==id).map(h=>h.status==='pending'?{...h,status:'superseded'}:h).slice(0,99);s.history.unshift({id,created_at:now(),source:p.source,status:changes.length?'pending':'applied'});if(changes.length)s.pending_import={id,created_at:now(),source:p.source,copies:p.copies,rows:p.rows,reductions:changes};else{await backup(env,s);applySnapshot(s,p,id);}await save(env,s,revision);return {id,unchanged:false,copies:p.copies,rows:p.rows,reductions:changes,applied:changes.length?null:{source:p.source}};}
function csv(rows){const columns=['name','quantity','printing_key','nonfoil','foil','zone','decks','notes','source_rows','value','priced_copies','fetched_at'];const cell=v=>{if(Array.isArray(v))v=v.join('; ');let s=String(v??'');if(/^[=+\-@]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\ufeff'+[columns.map(cell).join(','),...rows.map(r=>columns.map(k=>cell(r[k])).join(','))].join('\r\n');}
export default {async fetch(request,env,ctx){
 const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);
 if(!['GET','HEAD'].includes(request.method)){const origin=request.headers.get('origin');if(origin&&origin!==url.origin)return json({detail:'Requests must come from this site.'},403);}
 try{
 const {s,revision}=await load(env);const path=url.pathname.slice(4),q=url.searchParams;const method=request.method;const body=async()=>{const text=await request.text();if(text.length>250000)throw Error('Request is too large.');return JSON.parse(text||'{}');};
 if(method==='GET'&&['/state','/collection','/wishlist','/export'].includes(path)){
  const cards=await cardRows(env),inv=new Inventory(s,cards);
  if(path==='/collection')return json(inv.collection());
  if(path==='/state'){if(s.price_job.running && Date.now()-new Date(s.price_job.attempted_at||0).getTime()>120000) s.price_job.running=false;const collection=inv.collection();const summary={copies:collection.reduce((a,c)=>a+c.quantity,0),unique_cards:new Set(inv.holdings.map(h=>h.identity)).size,printings:collection.length,foil_copies:collection.reduce((a,c)=>a+c.foil,0),value:Math.round(collection.reduce((a,c)=>a+(c.value??0),0)*100)/100,priced_copies:collection.reduce((a,c)=>a+c.priced_copies,0),unresolved:collection.filter(c=>c.match_status!=='matched').length,issues:s.issues.length};if(s.holdings.length && !s.price_job.running&&(!s.settings.last_price_success||Date.now()-new Date(s.settings.last_price_success).getTime()>86400000)&&(!s.price_job.attempted_at||Date.now()-new Date(s.price_job.attempted_at).getTime()>3600000)){s.price_job={...s.price_job,attempted_at:now(),running:true};await save(env,s,revision);ctx.waitUntil(priceRefresh(env,false));}return json({...s,summary,decks:inv.decks.map(d=>inv.deck(d.id)),holdings:undefined,entries:undefined,matches:undefined,history:undefined,issues:undefined});}
  const ids=new Set((q.get('deck_ids')||'').split(',').filter(Boolean).map(Number)),mode=q.get('mode')||'assembled';if([...ids].some(x=>!Number.isSafeInteger(x)))throw Error('Invalid deck selection.');if(path==='/wishlist')return json(inv.wishlist(ids,mode));
  const kind=q.get('kind')||'collection',zone=q.get('zone')||'all';let rows;if(kind==='collection')rows=inv.collection().filter(c=>normalized(`${c.name} ${c.set_code} ${c.card_type}`).includes(normalized(q.get('q')||''))&&(!q.get('color')||c.color.includes(q.get('color')))&&(!q.get('type')||c.card_type.includes(q.get('type')))&&(q.get('foil')!=='true'||c.foil>0));else if(kind==='deck')rows=inv.deck(Number(q.get('deck_id'))).entries.filter(e=>zone==='all'||zone===e.zone);else if(kind==='missing')rows=inv.wishlist(ids,mode).items;else throw Error('Choose a collection, deck, or missing-card export.');const format=q.get('format')||'txt';if(!['txt','csv'].includes(format))throw Error('Choose TXT or CSV.');return new Response(format==='txt'?textExport(rows):csv(rows),{headers:{'Content-Type':format==='txt'?'text/plain;charset=utf-8':'text/csv;charset=utf-8','Content-Disposition':`attachment; filename="${kind}.${format}"`,'cache-control':'no-store'}});
 }
 if(path==='/issues'&&method==='GET'){const matches=[];for(const [printing_key,m]of Object.entries(s.matches)){const holdings=s.holdings.filter(h=>h.printing_key===printing_key);if(m.status!=='matched'&&holdings.length)matches.push({...m,printing_key,name:[...new Set(holdings.map(h=>h.name))].join(', '),source_rows:[...new Set(holdings.map(h=>h.source_row))].join(', ')});}return json({rows:s.issues,matches:matches.sort((a,b)=>a.name.localeCompare(b.name)),history:s.history});}
 if(path==='/upload'&&method==='POST'){const size=Number(request.headers.get('content-length')||0);if(size>MAX_BYTES)return json({detail:'Workbook exceeds 4 MB.'},413);const reader=request.body.getReader(),parts=[];let n=0;while(true){const r=await reader.read();if(r.done)break;n+=r.value.byteLength;if(n>MAX_BYTES){await reader.cancel();return json({detail:'Workbook exceeds 4 MB.'},413);}parts.push(r.value);}const raw=new Uint8Array(n);let offset=0;for(const p of parts){raw.set(p,offset);offset+=p.length;}const p=await parseWorkbook(raw.buffer,request.headers.get('x-workbook-name')||'inventory.xlsx');return json(await stage(env,s,revision,p,raw));}
 if(path==='/import'&&method==='POST')return json({unchanged:true,copies:s.holdings.reduce((a,h)=>a+h.quantity,0),reductions:[]});
 const imp=path.match(/^\/import\/([^/]+)\/(apply|dismiss)$/);if(imp&&method==='POST'){if(s.pending_import?.id!==imp[1])throw Error('This preview was superseded. Review the latest workbook.');if(imp[2]==='apply'){const row=await env.DB.prepare('SELECT payload FROM imports WHERE id=?').bind(imp[1]).first();if(!row)throw Error('Import not found.');await backup(env,s);applySnapshot(s,JSON.parse(row.payload),imp[1]);}else s.pending_import=null;s.history=s.history.map(h=>h.id===imp[1]?{...h,status:imp[2]==='apply'?'applied':'dismissed'}:h);await save(env,s,revision);return json({updated:true});}
 if(path==='/settings'&&method==='PATCH'){const data=await body();if(data.currency&&!['EUR','USD'].includes(data.currency))throw Error('Currency must be EUR or USD.');if(data.currency)s.settings.currency=data.currency;await save(env,s,revision);return json(s.settings);}
 const deck=path.match(/^\/decks(?:\/(\d+))?(\/active)?$/);if(deck&&['POST','PUT','DELETE'].includes(method)){let d=deck[1]?s.decks.find(d=>d.id===Number(deck[1])):null;if(deck[1]&&!d)throw Error('Deck not found.');if(method==='DELETE'){await backup(env,s);s.decks=s.decks.filter(x=>x.id!==d.id);s.entries=s.entries.filter(e=>e.deck_id!==d.id);}else{const data=await body();if(typeof data.active!=='boolean')throw Error('Active must be true or false.');if(deck[2])d.active=Number(data.active);else{const name=String(data.name||'').trim();if(!name||name.length>100)throw Error('Give the deck a name of up to 100 characters.');if(!formats.has(data.format))throw Error('Choose a supported format.');const entries=parseDecklist(data.decklist||'');if(entries.length>1000)throw Error('A deck can contain up to 1,000 distinct entries.');if(!d){d={id:Math.max(0,...s.decks.map(d=>d.id))+1,priority:0,source_label:null};s.decks.push(d);}Object.assign(d,{name,format:data.format,active:Number(data.active),seeded:0,updated_at:now()});s.entries=s.entries.filter(e=>e.deck_id!==d.id);let next=Math.max(0,...s.entries.map(e=>e.id))+1;for(const e of entries)s.entries.push({...e,id:next++,deck_id:d.id});}}await save(env,s,revision);return json({id:d?.id,updated:true});}
 if(path==='/prices/refresh'&&method==='POST'){if(s.price_job.running)return json(s.price_job);s.price_job={...s.price_job,running:true,attempted_at:now(),error:''};await save(env,s,revision);ctx.waitUntil(priceRefresh(env,q.get('force')==='true'));return json(s.price_job);}
 if(path==='/cards/search'&&method==='GET'){const query=String(q.get('q')||'').trim();if(!query||query.length>200)throw Error('Enter a card name or Scryfall query.');const result=await scryfall('/cards/search?unique=prints&q='+encodeURIComponent(query));return json(result.data.slice(0,50));}
 if(path==='/matches/confirm'&&method==='POST'){const data=await body();if(!s.matches[data.printing_key]||!(/^[0-9a-f-]{36}$/i).test(data.card_id))throw Error('Choose a valid printing.');const c=await scryfall('/cards/'+data.card_id);await putCards(env,[c]);s.matches[data.printing_key]={status:'matched',card_id:c.id,confirmed:true,message:'',checked_at:now()};await save(env,s,revision);return json({matched:true});}
 if(path==='/backup'&&method==='GET')return new Response(await backup(env,s),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="mtg-vault-backup.json"','cache-control':'no-store'}});
 return json({detail:'This action is unavailable.'},404);
 }catch(e){console.error('MTG Vault:',e.message);return json({detail:e.message||'Unable to load the collection. Please try again.'},e.message?.includes('another tab')?409:400);}
}};
